; align this with zero or fix getnextbeanaisle

BeanRandomTable:
        db    $02, $04, $06, $08, $0A, $0C, $0E, $10, $12
        db    $06, $0E, $02, $04, $12, $0A, $08, $0C, $10
        db    $02, $04, $06, $08, $0A, $0C, $0E, $10, $12
        db    $06, $0E, $02, $04, $12, $0A, $08, $0C, $10

BeanRandomTableY:
        db    $F3, $E6, $ED, $F6, $EB, $E2, $EB, $F1, $E9
        db    $C3, $CD, $BD, $CA, $BA, $AD, $BF, $B0, $BD
        db    $F3, $E6, $ED, $F6, $EB, $E2, $EB, $F1, $E9
        db    $C3, $CD, $BD, $CA, $BA, $AD, $BF, $B0, $BD